### ISSUE TITLE
Running mopidy as a service without root privileges

### ISSUE THREAD

**Issue by jgeisler0303** [9and3r/mopidy-touchscreen#15]
Hi,
I would like to share how I got mopidy to run as a service without root privileges.
First the prerequisites:
- I run the latest Raspbian Jessie, Version May 2016
- I have a hy28b touch screen

Further, I assume you have your touch screen running and bound to `/dev/fb1` and your touch input linked to `/dev/input/touchscreen`. The first is achieved by adding a line like `dtoverlay="your device"` to `/boot/config.txt` where `"your device"`is chosen from [this list](https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README) and possibly augmented with appropriate parameter settings. For the latter your might have to add another `dtoverlay`-line to your `/boot/config.txt`, depending on your touch input device. For my device this is not necessary as the touch driver is included in the display driver.
Finally you must link your touch input to `/dev/input/touchscreen` and calibrate it as described [here](https://github.com/notro/fbtft/wiki/FBTFT-on-Raspian#tslib-sdl-pygame). You may omit the creation of the files for setting the environment variables and run `sudo TSLIB_FBDEVICE=/dev/fb1 TSLIB_TSDEVICE=/dev/input/touchscreen ts_calibrate`instead.

You may also send boot log to the touch screen by adding this to the end of the one and only line in `/boot/cmdline.txt`: `fbcon=map:10`.

What follows now is the actual solution to letting run mopidy as a service without root privileges. I had to try many different approaches and I hope I recall everything that finally led to success correctly. If you encounter a problem in recreating this, give me a shout, maybe I missed something important.
- Downgrade the pygame library because the latest version in Jessie doesn't work for some reason. Follow [these instructions](https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/pitft-pygame-tips#ensure-you-are-running-sdl-1-dot-2).
- Add the mopidy user to the video, tty and input groups like `usermod -a -G video mopidy`, `usermod -a -G tty mopidy`, `usermod -a -G input mopidy`.
- Now, delete the link that starts a login process on the frame buffer of your touchscreen: `sudo rm /etc/systemd/system/getty.target.wants/getty@tty1.service`
- And finally, add the following lines to `/lib/systemd/system/mopidy.service` in the `[Service]` section:

```
  StandardInput=tty-fail
  StandardOutput=tty
  TTYPath=/dev/tty1
```
- Now edit the `/etc/mopidy/mopidy.conf` to your needs. And of course install Mopidy-Touchscreen and configure it as well
- If you now enable your mopidy service like `sudo systemctl enable mopidy` and `sudo reboot` it should run the touch UI on your TFT after startup.

Have fun and many thanks to the developers of this great little application.

**Comment by ghost** [comment]
Thanks for the detailed tutorial. It will be very helpful.
I tried a lot of different configurations and I was never able to run it without sudo.

I will add a link in the readme to  this tutorial.

**Comment by araczkowski** [comment]
same thing in my case, I stuck on this point and as a workaround I used rc.local
but finally it works - thanks!
