### ISSUE TITLE
Installing mopidy-touchscreen disables web interface on Pi MusicBox

### ISSUE THREAD

**Issue by wit07** [9and3r/mopidy-touchscreen#18]
Using last Pi MusicBox version (0.6.0), after installing mopidy-touchscreen (via 'pip install Mopidy-Touchscreen') disables web interface so I can't control mopidy via http.

**Comment by 9and3r** [comment]
Sorry for the late response :S
Mopidy-Touchscreen requires a newer version than the included on Pi MusicBox 0.6.0, so it is probably installing the new version and breaking things in musicbox.
