### ISSUE TITLE
Calibration 7" RaspberryPi touchscreen

### ISSUE THREAD

**Issue by andlo** [9and3r/mopidy-touchscreen#24]
I got it working :) but touch curser dosnt follow touch - so calibration is bad. 

How do I calibrate so touch actualy works ?

**Comment by 9and3r** [comment]
I do not have the official touchscreen, but I used these commands to calibrate my display:

`sudo apt-get install evtest tslib libts-bin`
`sudo TSLIB_FBDEVICE=/dev/fb1 TSLIB_TSDEVICE=/dev/input/touchscreen ts_calibrate`

**Comment by andlo** [comment]
Didnt work for me on a pimusicbox installation :( 

Now I try installing raspbian, and on that mopidy-touchscreen. This dosnt work either :( as mopidy-touchscreen says:

```
pi@raspberrypi:~ $ sudo pip --disable-pip-version-check install Modipy-touchscreen
Collecting Modipy-touchscreen
  Could not find a version that satisfies the requirement Modipy-touchscreen (from versions: )
No matching distribution found for Modipy-touchscreen

```

**Comment by defec8edc0de** [comment]
Same issue here.
How can I calibrate the original 7" Raspberry Pi touchscreen in Mopidy on PiMusicBox?

FYI: After installing evtest tslib libts-bin and trying your command above, I get:
`root@Music:Box~# TSLIB_FBDEVICE=/dev/fb1   
root@Music:Box:~# TSLIB_TSDEVICE=/dev/input/touchscreen   
root@Music:Box:~# ts_calibrate   
ts_open: No such file or directory`

According to this forum thread: https://discourse.mopidy.com/t/mopidy-touchscreen-with-7-original-pi-display/1442
It could be that the SDL version has to be downgraded to 1.2.0, unfortunately, I already had problems installing the SDL manually on the pi musicbox (see last post in this thread: https://www.raspberrypi.org/forums/viewtopic.php?t=82557 ).

I also noticed that the Pi crashes and restarts when choosing a song on a spotify playlist that contains non ascii characters in the title, such as Chinese characters.
