### ISSUE TITLE
Cursor at false

### ISSUE THREAD

**Issue by ArthurJam** [9and3r/mopidy-touchscreen#5]
Hello,

I have a raspberry with a touchscreen.
When i put the cursor option at false, I can't click on all screen.
Just the first and the last is be triggered.

Thanks for your work.

**Comment by 9and3r** [comment]
Is the touchscreen working fine with cursor option set to true?
This options calls to <a href="http://www.pygame.org/docs/ref/mouse.html#pygame.mouse.set_visible">pygame.mouse.set_visible</a>

I don't understand what you mean with "Just the first and the last is be triggered."  If you mean that it is only detected when you press on the touchscreen and when you release and not when you move while pressed, this is normal behavior.

**Comment by ArthurJam** [comment]
Yes the touchscreen working fine with cursor option set to true.
But where the option is set to false, the bottom menu is not working.
I just can press and enter in the first and last menu. I dont try to press and move.
It s probably a bug with pygame and my touchscreen.

**Comment by 9and3r** [comment]
I will close this as it seems that is not related directly with mopidy-touchscreen. 
Maybe you could try to calibrate the screen just in case:
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/touchscreen-install-and-calibrate#manual-calibration
